# Generated by Django 5.2.1 on 2025-06-02 04:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Garage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_garage', models.CharField(max_length=100)),
                ('dia_chi', models.CharField(max_length=200)),
                ('so_dien_thoai', models.CharField(max_length=20)),
                ('dich_vu', models.TextField(help_text='Danh sách dịch vụ cung cấp')),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bien_so', models.CharField(max_length=20, unique=True)),
                ('hang_xe', models.CharField(max_length=50)),
                ('dong_xe', models.CharField(max_length=50)),
                ('nam_san_xuat', models.IntegerField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vehicles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_bao_duong', models.DateField()),
                ('noi_dung', models.TextField(help_text='Miêu tả công việc bảo dưỡng (thay dầu, kiểm tra phanh, v.v.)')),
                ('chi_phi', models.DecimalField(decimal_places=2, max_digits=10)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='maintenance_records', to='core.vehicle')),
            ],
        ),
        migrations.CreateModel(
            name='Appointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ngay_gio', models.DateTimeField()),
                ('trang_thai', models.CharField(default='Chờ xác nhận', max_length=50)),
                ('ghi_chu', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to=settings.AUTH_USER_MODEL)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.garage')),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='core.vehicle')),
            ],
        ),
    ]
