# Generated by Django 5.2.1 on 2025-06-05 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='garage',
            options={'verbose_name': 'Garage', 'verbose_name_plural': 'Danh sách Garage'},
        ),
        migrations.AlterField(
            model_name='garage',
            name='dia_chi',
            field=models.CharField(default='Đang cập nhật', max_length=200),
        ),
        migrations.AlterField(
            model_name='garage',
            name='dich_vu',
            field=models.TextField(default='Đang cập nhật', help_text='Danh sách dịch vụ cung cấp'),
        ),
        migrations.AlterField(
            model_name='garage',
            name='so_dien_thoai',
            field=models.CharField(default='Đang cập nhật', max_length=20),
        ),
    ]
