# Generated by Django 5.2.1 on 2025-06-05 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_garage_options_alter_garage_dia_chi_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten', models.CharField(max_length=100)),
                ('mo_ta', models.TextField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Danh mục dịch vụ',
                'verbose_name_plural': 'Danh mục dịch vụ',
            },
        ),
        migrations.CreateModel(
            name='GarageService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ten_dich_vu', models.CharField(max_length=200)),
                ('mo_ta', models.TextField()),
                ('gia', models.DecimalField(decimal_places=0, max_digits=12)),
                ('thoi_gian_uoc_tinh', models.CharField(help_text='VD: 2-3 giờ', max_length=50)),
                ('trang_thai', models.BooleanField(default=True)),
                ('garage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chi_tiet_dich_vu', to='core.garage')),
                ('danh_muc', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.servicecategory')),
            ],
            options={
                'verbose_name': 'Dịch vụ của Garage',
                'verbose_name_plural': 'Dịch vụ của Garage',
            },
        ),
    ]
