# Generated by Django 5.2.1 on 2025-06-06 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_servicecategory_garageservice'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maintenancerecord',
            options={'verbose_name': 'Lịch sử bảo dưỡng', 'verbose_name_plural': 'Lịch sử bảo dưỡng'},
        ),
        migrations.RemoveField(
            model_name='maintenancerecord',
            name='ghi_chu',
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='chi_phi',
            field=models.DecimalField(decimal_places=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='maintenancerecord',
            name='noi_dung',
            field=models.TextField(),
        ),
    ]
