# Generated by Django 5.2.2 on 2025-06-07 13:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_maintenancerecord_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='ly_do',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='maintenance_period',
            field=models.IntegerField(default=90),
        ),
        migrations.AddField(
            model_name='maintenancerecord',
            name='ngay_den_han',
            field=models.DateField(blank=True, null=True, verbose_name='Ngày đến hạn bảo dưỡng'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='trang_thai',
            field=models.CharField(choices=[('pending', 'Chờ xác nhận'), ('confirmed', 'Đã xác nhận'), ('rejected', 'Từ chối'), ('completed', 'Hoàn thành'), ('cancelled', 'Đã hủy')], default='pending', max_length=20),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_type', models.CharField(choices=[('customer', 'Khách hàng'), ('garage_staff', 'Nhân viên Garage')], default='customer', max_length=20)),
                ('garage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.garage')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
