# Generated by Django 5.2.2 on 2025-06-07 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_appointment_ly_do_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appointment',
            name='trang_thai',
            field=models.CharField(choices=[('Chờ xác nhận', 'Chờ xác nhận'), ('Đã xác nhận', 'Đã xác nhận'), ('Từ chối', 'Từ chối'), ('Hoàn thành', 'Hoàn thành'), ('Đã hủy', 'Đã hủy')], default='Chờ xác nhận', max_length=20),
        ),
    ]
