# Generated by Django 5.2 on 2025-06-11 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_appointment_trang_thai'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='is_point_approved',
            field=models.BooleanField(default=False, verbose_name='Duyệt điểm tích lũy'),
        ),
    ]
