# Generated by Django 5.2 on 2025-06-11 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_maintenancerecord_is_point_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='loyalty_points',
            field=models.IntegerField(default=0, verbose_name='Điểm tích lũy'),
        ),
    ]
