# Generated by Django 5.2 on 2025-06-12 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_userprofile_loyalty_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='point_status',
            field=models.CharField(choices=[('pending', 'Chờ duyệt'), ('approved', 'Đã duyệt'), ('rejected', 'Bị từ chối')], default='pending', max_length=20, verbose_name='Trạng thái tích điểm'),
        ),
    ]
