# Generated by Django 5.2 on 2025-06-12 18:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_pointhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='garage',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.garage', verbose_name='Garage thực hiện'),
        ),
    ]
