# Generated by Django 5.2 on 2025-06-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_maintenancerecord_garage'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenancerecord',
            name='is_point_rejected',
            field=models.BooleanField(default=False, verbose_name='Từ chối tích điểm'),
        ),
    ]
